### PR TITLE
Create in memory if no file was passed in

### PR DESCRIPTION
**Pull request by SunboX**

### CODE REVIEW

**Comment by 2upmedia** [comment]
Hi @SunboX. Could you provide a realistic use-case for this?

**Comment by SunboX** [comment]
Hi @2upmedia n.p. :smile: 

This is my "use case":

```php
header('Content-type: application/csv; charset=Windows-1252');
header('Content-Disposition: attachment; filename=export.csv');
header('Pragma: no-cache');
header('Expires: 0');

$qb = $entityManager->createQueryBuilder()
    ->from('Item', 'i')
    ->select('i');

$items = $qb->getQuery()->execute();

$file = new \SplTempFileObject();
$file->setCsvControl(';');
$file->setFlags(\SplFileObject::DROP_NEW_LINE);

$row = array();
$row[] = 'Col 1';
$row[] = 'Col 2';
$row[] = 'Col 3';

foreach ($row as $i => $item) {
    $row[$i] = iconv('UTF-8', 'Windows-1252', $item);
}

$file->fputcsv($row, ';', '"');

foreach ($items as $i) {

    $row = array();

    $row[] = $vacation->getCol1();
    $row[] = $vacation->getCol2();
    $row[] = $vacation->getCol3();

    foreach ($row as $i => $item) {
        $row[$i] = iconv('UTF-8', 'Windows-1252', $item);
    }

    $file->fputcsv($row, ';', '"');
}

// header('Content-Length: ' . $file->getSize()); // <- does not works with SplTempFileObject

$file->fseek(0);
$file->fpassthru();

exit;
```

**Comment by jwage** [comment]
Can you fix code formatting issues and rebase?

**Comment by jwage** [comment]
@SunboX do you still want to get this merged in? If so, can you fix this branch up and add some tests?

**Comment by SunboX** [comment]
No, I do not need this anymore. Thanks, anyway.

**Pull request closed without merging**
