### PR TITLE
Add utf8 bom for ms excel

### PR DESCRIPTION
**Pull request by itcrab**
Hi, Jonathan!

In one of my project I have a problem with cyrillic symbols in generated CSV-file.

We have simple source:

``` php
require_once __DIR__ . '/vendor/autoload.php';

$writer = new \EasyCSV\Writer('write.csv');
$writer->writeFromArray(array(
    'колонка 1, колонка 2, колонка 3',
    array('значение 1', 'значение 2', 'значение 3')
));
```

And when we open it CSV-file in MS Excel take this:
image

For solve this problem I do this PR. Now you may set flag `$isNeedBOM` for give know `Writer` to insert UTF-8 BOM symbol in start CSV-file. When you do reading this CSV-file we checks exists UTF-8 BOM symbol and if it true - remove from first line.

Some source:

``` php
$writer = new \EasyCSV\Writer('write.csv', 'r+', true);
$writer->writeFromArray(array(
    'колонка 1, колонка 2, колонка 3',
    array('значение 1', 'значение 2', 'значение 3')
));
```

Give us good result on MS Excel:
image

I add small tests for this PR and if you see any more tests I will be add its.

### CODE REVIEW

**Comment by itcrab** [comment]
@jwage ping

**Comment by sharipoutra5** [comment]
I agree and I want to learn more

**Comment by itcrab** [comment]
@jwage ping

**Comment by itcrab** [comment]
@jwage ping

**Comment by simwodb1** [comment]
good

**Comment by itcrab** [comment]
@jwage ping

**Comment by itcrab** [comment]
@jwage you may merge my pull request?

**Comment by jwage** [comment]
:+1: sorry for the delay.

**Comment by hussain2022a** [comment]
Hussain @ #

>

**Pull request merged**
